name: y99
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  device_preview: ^1.2.0
  get: ^4.7.2
  gap: ^3.0.1
  firebase_core: ^3.13.0
  firebase_auth: ^5.3.4
  flutter_localization: ^0.2.2
  intl: ^0.19.0
  google_fonts: ^6.2.1
  flutter_easyloading: ^3.0.5
  font_awesome_flutter: ^10.7.0
  pin_code_fields: ^8.0.1
  flutter_launcher_icons: ^0.14.3
  dio: ^5.8.0+1
  get_storage: ^2.0.3
  pretty_dio_logger: ^1.3.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/logo/
     - assets/banner/
     - assets/icon/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo/logosplash.png"  # Đường dẫn đến file icon
  adaptive_icon_background: "#FFFFFF"  # Màu nền cho icon trên Android (Adaptive Icon)
  adaptive_icon_foreground: "assets/logo/logosplash.png"
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
